### ISSUE TITLE
Feature: "INI" style file parsing

### ISSUE THREAD

**Issue by philips** [ccding/go-config-reader#1]
systemd and git have settled on "ini" style files. Lots of people are used to handling them now so it would be good to just follow this same format.

```
[color]
    ui = true

[alias]
    ribbon = tag --force _ribbon origin/master
    catchup = log --patch --reverse --topo-order _ribbon..origin/master
```

This package might already do it. http://godoc.org/code.google.com/p/gcfg

**Comment by ccding** [comment]
added "INI" style file parsing, while doesn't support these style of comments

```
ui = true ; This is the UI settting
```

or

```
ui = true // This is the UI settting
```

or

```
ui = true # This is the UI settting
```

This means it only supports whole line comments now.

**Comment by philips** [comment]
Cool, so sections are supported already?

**Comment by philips** [comment]
It would be great to have the sections tested in the example and some _test.go files.

**Comment by ccding** [comment]
yes, you can read like

```
config, err := config.Read("filename.conf")
if err != nil {
    print config["color.ui"]
}
```

will add test later

**Comment by xiang90** [comment]
@ccding  This is cool. Can you add a function to allow application to re-write the conf file?

**Comment by ccding** [comment]
added `WriteTo(filename string)` function, which allows write the configuration to `filename`. This loses all the comments and reorganizes the structure. Write() function is a little bit complicated, I will do it later.
